### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by brw314** [rnewman/clj-apache-http#2]
Rich, sorry to bother you again but I cant seem to get it to  run (inside emacs, I've given up on classpaths for repl in a dos window, they just don't seem to work under windows, other  people on the list have had problems)

I have a file with just this:
(require ['com.twinql.clojure.http :as 'http])

when I load-file, I get this

java.lang.NoClassDefFoundError: Could not initialize class com.twinql.clojure.http__init (NO_SOURCE_FILE:0)
  [Thrown class clojure.lang.Compiler$CompilerException]

this is my .emacs which generally works for compojure and others

 (setq swank-clojure-classpath
     (list  "c:/compojure/compojure.jar" "c:/clojure-1/clojure-1.1.0/compojure-contrib.jar" "C:/clojure/clj-apache-http/clj-apache-http.jar") )

 Directory of c:\clojure\clj-apache-http

02/16/2010  09:14 PM            65,418 clj-apache-http.jar
               1 File(s)         65,418 bytes

**Comment by rnewman** [comment]
You need clojure.jar, clojure-contrib.jar, and all of clj-apache-http's dependencies — the Apache HttpCore and Apache HttpComponents jars — on your classpath.

Everything Ant uses to build that jar: take a look in build.xml.
